[package]
name = "skimr"
version = "0.1.0"
authors = ["p1g30n <anatol@riseup.net>"]
edition = "2018"

[dependencies]
url = "1.7.2"
regex = "1.1.2"
select = "0.4.2"
scraper = "0.9.2"
reqwest = "0.9.11"
lazy_static = "1.3.0"

[[bin]]
name = "skimr"
path = "src/main.rs"
